### ISSUE TITLE
react-native-masonry-list Image failed to load.

### ISSUE THREAD

**Issue by EdisonDevadoss** [Luehang/react-native-masonry-list#11]
It shows the warning message. Then nothing is shown. 
Earlier it works well. Now show warn. Help me.

 ```
   "react": "16.6.3",
    "react-native": "0.58.6",
    "react-native-masonry-list": "^2.8.1",
```

**Comment by Luehang** [comment]
This is most likely server side issues.  It throws that message because it was not able to fetch the image.

**Comment by Luehang** [comment]
If an image is unable to be fetched, it will throw a warning and fail silently.

**Comment by EdisonDevadoss** [comment]
Thank you for your response.

**Comment by Kogilapriadarsini** [comment]
@Luehang : FastImage is able to fetch the images from server, because there is an option to set httpHeaderFields. Is there a similar option in case of masonry List? I tried setting completeCustomComponent, but its render method is getting called only after the image is downloaded. Please let me know the possibilities.
