### ISSUE TITLE
onPressImage is not working

### ISSUE THREAD

**Issue by smubarak-ali** [Luehang/react-native-masonry-list#14]
Hi there,

First of all, thank you for this wonder lib... It's the best one, I have tried a few and this is the only one which is actually working in all aspects.

I am facing an issue when trying to attach the function on onPressImage

```
goToDetails = (item: any, index: number) => {
    console.log("details: ", item);
}

<MasonryList
       key="2"
       images={images}
       columns={2}
       backgroundColor={colors.ghost_white}
       imageContainerStyle={{
               borderRadius: 7
       }}
       renderIndividualHeader={(data: MasonryImage) => {
               return <Text style={styles.pinHeaderStyle}>{data.title}</Text>
       }}
       customImageComponent={FastImage}
       customImageProps={fastProps}
       onPressImage={this.goToDetails}
/>
```
The goToDetails is not being triggered... I noticed when I was tapping the image ruthlessly, I see 2, 3 times it printed the console.

**Comment by Luehang** [comment]
Hi,

A temporarily fix is to fully customize the image component of the `react-native-masonry-list`.  The description is shown below on how to use it.  If you would like an example, let me know.  I would be happy to help you out.

<br/>

# :large_blue_diamond: Props
| Props                         | Description                                                                                                                                                                                    | Type              | Default |
|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|---------|
| `completeCustomComponent`     | Custom function to return a fully custom component for each image.  `({ source: object, style: { width: number, height: number, margin: number }, data: object }) => React.Element`  This function must return a React Component and it is required to have the source and style for the component to display proper masonry. | `Function` | |

<br/>

The issue is being resolved at the moment.  Thanks for your patience.

**Comment by Luehang** [comment]
You're using mostly customized props so it's recommended to use `completeCustomComponent`.  `FastImage` is another third party package that will be a lot more compatible with `react-native-masonry-list` in future releases.

**Comment by smubarak-ali** [comment]
Hi @Luehang 
Thank you for all the help! I managed to get it working. I am posting my code below, for reference.
Thank you once again for this wonderful library!

Modified masonry list
```
<MasonryList
                key="2"
                images={images}
                columns={2}
                backgroundColor={colors.ghost_white}
                imageContainerStyle={{
                    borderRadius: 7
                }}
                renderIndividualHeader={(data: MasonryImage) => {
                    return <Text style={styles.pinHeaderStyle} onPress={() => Actions.details({ id: `${data.id}`})}>{data.title}</Text>
                }}
                completeCustomComponent={(props: any) => <MasonryCustomComponent {...props} />}
            />
```

Custom complete component
```
interface Props {
    source: any;
    data: MasonryImage;
    style: {
        width: number;
        height: number;
        margin: number;
    }
}

const MasonryCustomComponent: React.SFC<Props> = (props) => {
    return (
        <TouchableOpacity onPress={() => Actions.details({ id: `${props.data.id}` })}>
            <FastImage resizeMode="stretch" source={{uri: props.data.uri}} style={{width: props.style.width, height: props.style.height, margin: props.style.margin}} />
        </TouchableOpacity>
    );
}

export default MasonryCustomComponent;
```
