### ISSUE TITLE
Make the images work with search

### ISSUE THREAD

**Issue by nathan-rumbleon** [Luehang/react-native-masonry-list#4]
Hi,

I was trying to use this with Algolia search but noticed the list would not update when the images change. I added the following code to the bottom of componentWillReceiveProps in MasonryList.js and this seem's to fix the issue. Just want to make sure this would be the best approach?

`else if(nextProps.images !== this.props.images) {
			this.resolveImages(
				nextProps.itemSource,
				nextProps.images,
				nextProps.layoutDimensions,
				nextProps.columns,
				nextProps.sorted
			);
		}`

**Comment by Luehang** [comment]
Hi,

Thanks for letting me know.

The best approach that I can think of was to group that statement with the other if statements and to use an **or** comparison operator.  The next feature update includes that along with many other things.

```bash
$ npm install --save react-native-masonry-list@2.6.0
```
or
```bash
$ yarn add react-native-masonry-list@2.6.0
```

You should make a **pull request** the next time you want to contribute since you seem more experienced to pick out the problem in the code.

If you would like to check out what the next feature includes, check out the [version releases](https://github.com/Luehang/react-native-masonry-list/releases) or a more detail update at the [commit section](https://github.com/Luehang/react-native-masonry-list/commits/master).

Thanks again for pointing that out.  Always trying to improve the package.

From,

Lue Hang
